version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      ignore:
          - dependency-type: 'development' # Ignore dev dependencies
      allow:
          - dependency-type: 'production' # Only allow to update production deps
