version: 1
update_configs:
    - package_manager: 'javascript'
      directory: '/'
      update_schedule: 'daily'
      default_reviewers:
          - 'Linux123123'
      default_labels:
          - 'package-update'
          - 'dependabot'
