name: Node.js Package

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn build
      - name: Publish Package
        env:
          GITHUB_NPM_CONFIG_REGISTRY: 'https://npm.pkg.github.com/'
          NPM_NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org/'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
          NPM_NPM_TOKEN: ${{ secrets.NPM_NPM_TOKEN }}
        run: npx semantic-release
      - name: BuildDocs
        if: github.ref == 'refs/heads/master'
        run: yarn docs:build
      - name: Deploy Docs
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs
